export const APP_CONFIG = {
  appName: 'SchemeSahay',
  tagline: 'Find Government Schemes Made For You.',
  assistantName: 'AI Assistant',
  assistantShortName: 'Asha',
  assistantPersona: 'Empathetic, clear, and compassionate civic assistant for Indian citizens',
  contactHelpline: '1800-115-555',
  nationalPortalUrl: 'https://myscheme.gov.in',
  supportedLanguages: [
    { code: 'en', name: 'English', nativeName: 'English', voiceCode: 'en-IN' },
    { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', voiceCode: 'hi-IN' },
    { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', voiceCode: 'te-IN' },
    { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', voiceCode: 'ta-IN' },
    { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', voiceCode: 'kn-IN' },
    { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', voiceCode: 'ml-IN' },
    { code: 'mr', name: 'Marathi', nativeName: 'मराठी', voiceCode: 'mr-IN' },
    { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', voiceCode: 'bn-IN' },
  ],
  categories: [
    { id: 'education', icon: 'GraduationCap', label: 'Education & Scholarships', labelKey: 'cat_education', color: 'emerald' },
    { id: 'agriculture', icon: 'Wheat', label: 'Agriculture & Rural', labelKey: 'cat_agriculture', color: 'amber' },
    { id: 'housing', icon: 'Home', label: 'Housing & Shelter', labelKey: 'cat_housing', color: 'blue' },
    { id: 'employment', icon: 'Briefcase', label: 'Employment & Skills', labelKey: 'cat_employment', color: 'purple' },
    { id: 'women', icon: 'Users', label: 'Women & Maternity', labelKey: 'cat_women', color: 'rose' },
    { id: 'healthcare', icon: 'HeartPulse', label: 'Health & Wellness', labelKey: 'cat_healthcare', color: 'teal' },
    { id: 'financial', icon: 'Coins', label: 'Financial & Subsidies', labelKey: 'cat_financial', color: 'cyan' },
    { id: 'senior_citizens', icon: 'UserCheck', label: 'Senior Citizens', labelKey: 'cat_senior_citizens', color: 'indigo' },
    { id: 'disability', icon: 'Accessibility', label: 'Disability Welfare', labelKey: 'cat_disability', color: 'orange' },
    { id: 'children', icon: 'Baby', label: 'Children & Family', labelKey: 'cat_children', color: 'pink' },
  ],
  indianStates: [
    'All India',
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
    'Delhi (NCT)',
    'Jammu & Kashmir',
    'Ladakh',
    'Puducherry',
    'Chandigarh',
  ],
};
