import React, { useState } from 'react';
import { History, LogOut, MessageSquarePlus, MoreHorizontal, Settings, Trash2, UserRound, X } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { useLanguage } from '../i18n/LanguageContext';

export const HistorySidebar: React.FC = () => {
  const { conversations, activeConversationId, selectConversation, startNewConversation, authUser, signOut, setIsProfileWizardOpen, deleteConversation } = useApp();
  const { language, setLanguage, languages } = useLanguage();
  const [openMenu, setOpenMenu] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [pendingDeleteId, setPendingDeleteId] = useState<string | null>(null);
  const [mobileOpen, setMobileOpen] = useState(false);
  const ordered = [...conversations].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));

  const content = <aside className={`${mobileOpen ? 'fixed inset-y-0 left-0 z-[60] w-[290px]' : 'hidden lg:flex w-[250px]'} bg-[#20252b] text-white flex-col shrink-0 border-r border-slate-700 shadow-[8px_0_24px_rgba(15,23,42,0.08)]`}>
    <div className="p-4 flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-black"><div className="w-8 h-8 rounded-xl bg-amber-400 text-slate-950 grid place-items-center">🇮🇳</div>Scheme<span className="text-amber-400">Sahay</span></div>{mobileOpen && <button onClick={() => setMobileOpen(false)} title="Close history"><X className="w-5 h-5 text-slate-300" /></button>}</div>
    <button onClick={() => { startNewConversation(); setMobileOpen(false); }} className="mx-3 mb-5 h-11 rounded-xl bg-amber-400 hover:bg-amber-300 text-slate-950 flex items-center justify-center gap-2 text-sm font-black shadow-sm"><MessageSquarePlus className="w-4 h-4" /> New conversation</button>
    <div className="px-4 pb-2 flex items-center gap-2 text-[10px] uppercase tracking-[0.16em] font-bold text-slate-400"><History className="w-3.5 h-3.5 text-teal-400" /> Recent history</div>
    <div className="px-2 overflow-y-auto flex-1 space-y-1">
      {ordered.map((conversation) => <div key={conversation.id} className={`w-full rounded-xl flex items-center gap-2.5 group transition-colors ${conversation.id === activeConversationId ? 'bg-slate-700 text-white border border-slate-600' : 'text-slate-300 hover:bg-slate-800 hover:text-white'}`}><button onClick={() => { selectConversation(conversation.id); setMobileOpen(false); }} className="min-w-0 flex-1 text-left px-3 py-3 flex items-start gap-2.5"><MessageSquarePlus className="w-4 h-4 mt-0.5 shrink-0 text-slate-500 group-hover:text-teal-300" /><span className="truncate text-xs font-semibold">{conversation.title}</span></button>{pendingDeleteId === conversation.id ? <div className="flex items-center gap-1 pr-2"><button onClick={() => { deleteConversation(conversation.id); setPendingDeleteId(null); }} className="text-[10px] font-black text-rose-300 hover:text-white" title="Confirm delete">Delete</button><button onClick={() => setPendingDeleteId(null)} className="text-[10px] text-slate-400 hover:text-white" title="Cancel delete">Cancel</button></div> : <button onClick={() => setPendingDeleteId(conversation.id)} className="p-2 mr-1 opacity-0 group-hover:opacity-100 text-slate-500 hover:text-rose-300 transition-opacity" title="Delete conversation"><Trash2 className="w-3.5 h-3.5" /></button>}</div>)}
    </div>
    <div className="p-3 border-t border-slate-700 relative"><button onClick={() => setOpenMenu(!openMenu)} className="w-full flex items-center gap-3 p-2 rounded-xl hover:bg-slate-800 text-left"><div className="w-8 h-8 rounded-full bg-amber-100 text-slate-800 grid place-items-center text-xs font-black">{authUser?.name.slice(0, 1).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="text-xs font-bold truncate">{authUser?.name}</div><div className="text-[10px] text-slate-400 truncate">{authUser?.email}</div></div><MoreHorizontal className="w-4 h-4 text-slate-400" /></button>{openMenu && <div className="absolute bottom-16 left-3 right-3 rounded-xl bg-white text-slate-800 p-1.5 shadow-2xl"><button onClick={() => { setIsProfileWizardOpen(true); setOpenMenu(false); }} className="w-full p-2.5 rounded-lg text-left text-xs font-bold hover:bg-slate-100 flex items-center gap-2"><UserRound className="w-4 h-4" /> Citizen profile</button><button onClick={() => { setSettingsOpen(true); setOpenMenu(false); }} className="w-full p-2.5 rounded-lg text-left text-xs font-bold hover:bg-slate-100 flex items-center gap-2"><Settings className="w-4 h-4" /> Settings</button><button onClick={signOut} className="w-full p-2.5 rounded-lg text-left text-xs font-bold text-rose-600 hover:bg-rose-50 flex items-center gap-2"><LogOut className="w-4 h-4" /> Log out</button></div>}</div>
  </aside>;

  return <><button onClick={() => setMobileOpen(true)} className="lg:hidden fixed bottom-5 left-5 z-40 w-12 h-12 rounded-2xl bg-[#20252b] text-amber-300 shadow-xl grid place-items-center" title="Open conversation history"><History className="w-5 h-5" /></button>{content}{settingsOpen && <div className="fixed inset-0 z-[70] bg-slate-950/50 flex items-center justify-center p-4"><div className="w-full max-w-sm bg-white rounded-2xl p-6 shadow-2xl text-slate-900"><div className="flex items-center justify-between mb-5"><div><h2 className="text-lg font-black">Settings</h2><p className="text-xs text-slate-500 mt-1">Manage your SchemeSahay experience.</p></div><button onClick={() => setSettingsOpen(false)} title="Close settings"><X className="w-5 h-5 text-slate-400" /></button></div><label className="block text-xs font-bold text-slate-700">Assistant language<select value={language} onChange={(event) => setLanguage(event.target.value as any)} className="mt-2 w-full h-11 rounded-xl border border-slate-300 px-3 text-sm bg-white">{languages.map((item) => <option key={item.code} value={item.code}>{item.nativeName}</option>)}</select></label><div className="mt-5 rounded-xl bg-teal-50 p-3 text-xs text-teal-900"><div className="font-bold">Account</div><div className="mt-1">{authUser?.email}</div></div><button onClick={signOut} className="mt-5 w-full h-11 rounded-xl border border-rose-200 text-rose-600 font-bold text-sm hover:bg-rose-50 flex items-center justify-center gap-2"><LogOut className="w-4 h-4" /> Log out</button></div></div>}</>;
};
