import { KnowledgeChunk } from '../shared/types.ts';

export const KNOWLEDGE_CHUNKS: KnowledgeChunk[] = [
  {
    id: 'chunk-pms-01',
    documentId: 'doc-edu-postmatric-2026-v3',
    schemeId: 'scheme-post-matric-scholarship',
    schemeName: 'Post-Matric Scholarship for SC/ST/OBC Students',
    section: 'Eligibility & Income Limits',
    pageNumber: 8,
    content: 'Under the Post-Matric Scholarship Scheme (Version 3.2, 2026), the annual household income ceiling from all sources is ₹2,50,000 per annum. Eligible students must have successfully passed Matriculation (10th standard) or Higher Secondary examination and be enrolled in a recognized post-matric course including ITI, Polytechnic Diploma, General Degree (BA, B.Sc, B.Com), Professional Degree (B.Tech, MBBS, LLB) and Postgraduate studies. Employed individuals earning a salary are excluded unless on unpaid study leave.',
    ministry: 'Ministry of Social Justice and Empowerment',
    sourceUrl: 'https://scholarships.gov.in/guidelines/postmatric2026.pdf',
    version: '3.2',
    lastVerified: '2026-08-22',
    status: 'ACTIVE',
    keywords: ['scholarship', 'income limit', 'post-matric', 'education', '250000', 'tuition fees', 'SC', 'ST', 'OBC']
  },
  {
    id: 'chunk-pms-02',
    documentId: 'doc-edu-postmatric-2026-v3',
    schemeId: 'scheme-post-matric-scholarship',
    schemeName: 'Post-Matric Scholarship for SC/ST/OBC Students',
    section: 'Benefits and DBT Disbursement',
    pageNumber: 14,
    content: 'The financial benefit consists of two components: 1. Full non-refundable tuition and institutional fees reimbursed directly to college or student account up to state fee fixation limits. 2. Annual maintenance allowance ranging from ₹4,000 to ₹13,500 per annum depending on academic group level (Group 1: Medical/Engineering, Group 2: Professional PG, Group 3: Degree courses, Group 4: Class 11 & 12). All payments are disbursed exclusively via Aadhaar Enabled Payment System (AEPS).',
    ministry: 'Ministry of Social Justice and Empowerment',
    sourceUrl: 'https://scholarships.gov.in/guidelines/postmatric2026.pdf',
    version: '3.2',
    lastVerified: '2026-08-22',
    status: 'ACTIVE',
    keywords: ['tuition reimbursement', 'maintenance allowance', 'DBT', 'AEPS', 'hosteler', 'day scholar']
  },
  {
    id: 'chunk-pmk-01',
    documentId: 'doc-agri-pmkisan-2026-v4',
    schemeId: 'scheme-pm-kisan-samman-nidhi',
    schemeName: 'PM Kisan Samman Nidhi (PM-KISAN)',
    section: 'Eligibility and Criteria',
    pageNumber: 5,
    content: 'PM-KISAN operational guidelines (Version 4.1, 2026) state that all landholding farmer families with cultivable land parcels registered in state land revenue records are eligible. A landholder family comprises husband, wife, and minor children. Exclusions include: Institutional landholders, constitutional post holders, serving/retired government employees (except Group D/Multi Tasking Staff), income tax payers in the previous assessment year, and professionals like doctors, engineers, and lawyers.',
    ministry: 'Ministry of Agriculture and Farmers Welfare',
    sourceUrl: 'https://pmkisan.gov.in/documents/PM_KISAN_Guidelines_2026.pdf',
    version: '4.1',
    lastVerified: '2026-08-22',
    status: 'ACTIVE',
    keywords: ['farmer', 'agriculture', 'PM-KISAN', 'cultivable land', 'income tax exclusion', 'landholder']
  },
  {
    id: 'chunk-pmk-02',
    documentId: 'doc-agri-pmkisan-2026-v4',
    schemeId: 'scheme-pm-kisan-samman-nidhi',
    schemeName: 'PM Kisan Samman Nidhi (PM-KISAN)',
    section: 'Financial Benefit & e-KYC',
    pageNumber: 12,
    content: 'Under PM-KISAN, the annual benefit of ₹6,000 is released in three equal four-monthly installments of ₹2,000 directly to bank accounts via Direct Benefit Transfer (DBT). Mandatory requirements for receiving installments include: 1. Aadhaar linked with bank account (NPCI mapper active). 2. Successful biometric or OTP-based e-KYC on pmkisan.gov.in. 3. Land record seeding (Bhulekh verification) completed by the State Agriculture Nodal Officer.',
    ministry: 'Ministry of Agriculture and Farmers Welfare',
    sourceUrl: 'https://pmkisan.gov.in/documents/PM_KISAN_Guidelines_2026.pdf',
    version: '4.1',
    lastVerified: '2026-08-22',
    status: 'ACTIVE',
    keywords: ['6000 rupees', '3 installments', '2000 DBT', 'e-KYC', 'land seeding', 'NPCI']
  },
  {
    id: 'chunk-pmay-01',
    documentId: 'doc-house-pmay-2026-v5',
    schemeId: 'scheme-pm-awas-yojana',
    schemeName: 'Pradhan Mantri Awas Yojana (PMAY-Urban & Gramin)',
    section: 'Income Categories & Eligibility',
    pageNumber: 12,
    content: 'PMAY guidelines (Version 5.0, 2026) define income categories: Economically Weaker Section (EWS) annual household income up to ₹3,00,000; Low Income Group (LIG) annual household income between ₹3,00,001 and ₹6,00,000. Beneficiary family must not own a pucca (all-weather permanent) house either in their name or in the name of any member of their family in any part of India. The female head of the family should be the primary owner or co-owner of the dwelling unit.',
    ministry: 'Ministry of Housing and Urban Affairs',
    sourceUrl: 'https://pmaymis.gov.in/guidelines_pmay2_2026.pdf',
    version: '5.0',
    lastVerified: '2026-08-22',
    status: 'ACTIVE',
    keywords: ['housing', 'PMAY', 'EWS', 'LIG', 'pucca house', 'female ownership', 'interest subsidy']
  },
  {
    id: 'chunk-pmjay-01',
    documentId: 'doc-health-pmjay-2026-v3',
    schemeId: 'scheme-ayushman-bharat-pmjay',
    schemeName: 'Ayushman Bharat PM-JAY',
    section: 'Coverage and Hospitalization',
    pageNumber: 8,
    content: 'Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana provides a health assurance cover of ₹5,00,000 per family per year for secondary and tertiary care hospitalisation. There is no restriction on family size, age, or gender. Pre-existing conditions are covered from day one. Services include medical examination, treatment, consultation, pre-hospitalization diagnostics (up to 3 days), medicines, and post-hospitalization discharge follow-up (up to 15 days).',
    ministry: 'Ministry of Health and Family Welfare',
    sourceUrl: 'https://nha.gov.in/guidelines/pmjay_sop_2026.pdf',
    version: '3.4',
    lastVerified: '2026-08-22',
    status: 'ACTIVE',
    keywords: ['ayushman card', '5 lakh', 'health insurance', 'cashless hospital', 'pre-existing diseases', 'NHA']
  },
  {
    id: 'chunk-pmmvy-01',
    documentId: 'doc-women-pmmvy-2026-v2',
    schemeId: 'scheme-pmmvy-maternity-benefit',
    schemeName: 'Pradhan Mantri Matru Vandana Yojana (PMMVY)',
    section: 'Maternity Cash Transfer Rules',
    pageNumber: 4,
    content: 'Under PMMVY 2.0 (Version 2.3, 2026), eligible pregnant women and lactating mothers receive ₹5,000 in two installments for their first child: First installment of ₹3,000 upon early pregnancy registration and at least one antenatal check-up (ANC); Second installment of ₹2,000 after child birth and primary vaccination (BCG, OPV, DPT, Hepatitis-B). For a second child, if the newborn is a girl child, an incentive of ₹6,000 is transferred in a single installment to celebrate the girl child.',
    ministry: 'Ministry of Women and Child Development',
    sourceUrl: 'https://wcd.nic.in/schemes/pmmvy_revised_norms_2026.pdf',
    version: '2.3',
    lastVerified: '2026-08-22',
    status: 'ACTIVE',
    keywords: ['maternity benefit', 'pregnancy', '5000 rupees', 'girl child 6000', 'ASHA', 'Anganwadi', 'vaccination']
  },
  {
    id: 'chunk-jvd-01',
    documentId: 'doc-state-ap-jvd-2026-v2',
    schemeId: 'scheme-ap-jagananna-vidya-deevena',
    schemeName: 'Andhra Pradesh Jagananna Vidya Deevena (RTF)',
    section: 'Eligibility & 100% Fee Reimbursement',
    pageNumber: 5,
    content: 'Andhra Pradesh Jagananna Vidya Deevena scheme reimburses 100% of college tuition fees for students pursuing Polytechnic, ITI, Degree, Engineering (B.Tech), Medicine, Pharmacy, MBA, and MCA in government and affiliated private institutions. Total annual family income must be under ₹2,50,000. Total landholding must not exceed 10 acres of wetland or 25 acres of dryland. The fee amount is credited directly to the mother’s Aadhaar-linked bank account in 4 quarterly releases.',
    ministry: 'Government of Andhra Pradesh',
    sourceUrl: 'https://jnanabhumi.ap.gov.in/docs/jvd_guidelines_2026.pdf',
    version: '2.2',
    lastVerified: '2026-08-22',
    status: 'ACTIVE',
    keywords: ['Andhra Pradesh', 'Jagananna Vidya Deevena', 'B.Tech', 'fee reimbursement', 'mother account', '250000 income']
  },
  {
    id: 'chunk-mudra-01',
    documentId: 'doc-fin-mudra-2026-v3',
    schemeId: 'scheme-pm-mudra-yojana',
    schemeName: 'Pradhan Mantri Mudra Yojana (PMMY)',
    section: 'Loan Categories and Terms',
    pageNumber: 6,
    content: 'Pradhan Mantri Mudra Yojana offers collateral-free business loans for manufacturing, processing, trading, and service activities: 1. Shishu: Loans up to ₹50,000 for new micro startups. 2. Kishore: Loans above ₹50,000 and up to ₹5,00,000 for buying equipment and inventory. 3. Tarun: Loans above ₹5,00,000 and up to ₹10,00,000 for expanding established enterprises. No processing fees for Shishu and Kishore loans; interest rate is linked to bank MCLR/RBLR with zero collateral security.',
    ministry: 'Ministry of Finance',
    sourceUrl: 'https://mudra.org.in/guidelines/mudra_2026.pdf',
    version: '3.1',
    lastVerified: '2026-08-22',
    status: 'ACTIVE',
    keywords: ['business loan', 'mudra', 'shishu', 'kishore', 'tarun', 'collateral free', '10 lakh']
  },
  {
    id: 'chunk-naps-01',
    documentId: 'doc-skill-naps-2026-v2',
    schemeId: 'scheme-national-apprenticeship-naps',
    schemeName: 'National Apprenticeship Promotion Scheme (NAPS-2)',
    section: 'Stipend Sharing & Certification',
    pageNumber: 7,
    content: 'NAPS-2 supports youth aged 14 to 35 years who have completed 5th, 8th, 10th, 12th, ITI, Diploma, or Degree. The Government of India pays 25% of the prescribed monthly stipend directly to the candidate bank account (DBT) up to a maximum of ₹1,500 per month. The industrial establishment pays the remaining 75% stipend. Upon successful completion and assessment, candidates receive the National Apprenticeship Certificate (NAC).',
    ministry: 'Ministry of Skill Development and Entrepreneurship',
    sourceUrl: 'https://apprenticeshipindia.gov.in/guidelines/naps_2026.pdf',
    version: '2.0',
    lastVerified: '2026-08-22',
    status: 'ACTIVE',
    keywords: ['apprenticeship', 'stipend', 'skill development', '1500 DBT', 'ITI', 'diploma', 'training']
  }
];
