import { LanguageCode } from './translations';

type ViewCopy = Record<string, string>;

const en: ViewCopy = {
  transparent: 'Transparent Civic Architecture', howTitle: 'How SchemeSahay Works', howSub: 'From official Ministry gazette documents to direct citizen empowerment with verified facts.', verifiedStep: 'Verified Step', compareTitle: 'Why SchemeSahay Solves the Welfare Discovery Gap', traditional: 'Traditional Government Search', schemeWay: 'SchemeSahay AI + Verified RAG',
  sourceBadge: 'Complete Civic Transparency', sourceTitle: 'Verified Official Government Sources', sourceIntro: 'SchemeSahay enforces a strict Primary Source grounding rule. Every piece of advice given by the AI Assistant or evaluated by our eligibility engine originates directly from official government documents and ministry orders.', ingested: 'Ingested Documents', grounding: 'Verified Grounding', academic: 'Active Academic Cycle', languages: 'Indian Languages', pipeline: 'Document Ingestion & RAG Lineage Architecture', pipelineSub: 'How official Ministry circulars are transformed into verifiable, citeable citizen knowledge.', registry: 'Official Document Registry', registrySub: 'Live verified repository of government policy PDFs', searchDocs: 'Search ministry or document...', document: 'Document Title & ID', ministry: 'Ministry Authority', version: 'Version', verified: 'Last Verified', status: 'Status', official: 'Official Link', pdf: 'PDF',
  aboutBadge: 'SchemeSahay Civic Mission', aboutTitle: 'Civic Welfare Access for Every Indian Citizen', aboutIntro: 'India administers hundreds of central and state welfare initiatives, yet millions of eligible citizens miss out due to complex documents, language barriers, and fragmented portals.', groundingPillar: '100% Primary Source Grounding', aiPillar: 'Asha: Empathetic Multilingual AI', privacyPillar: 'Privacy & Citizen Dignity', redirectPillar: 'Direct Official Redirection', disclaimer: 'Official Civic Disclaimer', disclaimerText: 'SchemeSahay is an independent civic information platform. While every effort is made to maintain fidelity with official ministry guidance, formal sanction of benefits rests solely with designated government authorities.'
};

const copies: Record<LanguageCode, ViewCopy> = {
  en,
  hi: { transparent: 'पारदर्शी नागरिक व्यवस्था', howTitle: 'स्कीम सहाय कैसे काम करता है', howSub: 'आधिकारिक मंत्रालय दस्तावेजों से सत्यापित जानकारी के साथ नागरिक सशक्तिकरण तक।', verifiedStep: 'सत्यापित चरण', compareTitle: 'स्कीम सहाय कल्याण योजनाओं की खोज में मदद क्यों करता है', traditional: 'पारंपरिक सरकारी खोज', schemeWay: 'स्कीम सहाय एआई और सत्यापित RAG', sourceBadge: 'पूर्ण नागरिक पारदर्शिता', sourceTitle: 'सत्यापित आधिकारिक सरकारी स्रोत', sourceIntro: 'स्कीम सहाय का हर उत्तर आधिकारिक सरकारी दस्तावेजों और मंत्रालय के आदेशों पर आधारित है।', ingested: 'शामिल दस्तावेज', grounding: 'सत्यापित आधार', academic: 'सक्रिय शैक्षणिक चक्र', languages: 'भारतीय भाषाएं', pipeline: 'दस्तावेज संग्रह और RAG संरचना', pipelineSub: 'आधिकारिक मंत्रालय परिपत्रों को सत्यापित नागरिक जानकारी में बदलने की प्रक्रिया।', registry: 'आधिकारिक दस्तावेज रजिस्टर', registrySub: 'सरकारी नीति PDF का सत्यापित भंडार', searchDocs: 'मंत्रालय या दस्तावेज खोजें...', document: 'दस्तावेज शीर्षक और आईडी', ministry: 'मंत्रालय प्राधिकरण', version: 'संस्करण', verified: 'अंतिम सत्यापन', status: 'स्थिति', official: 'आधिकारिक लिंक', pdf: 'PDF', aboutBadge: 'स्कीम सहाय नागरिक मिशन', aboutTitle: 'हर भारतीय नागरिक के लिए कल्याण तक पहुंच', aboutIntro: 'भारत में सैकड़ों कल्याण योजनाएं हैं, फिर भी जटिल दस्तावेजों, भाषा बाधाओं और अलग-अलग पोर्टलों के कारण कई पात्र नागरिक वंचित रह जाते हैं।', groundingPillar: '100% प्राथमिक स्रोत आधार', aiPillar: 'आशा: सहानुभूतिपूर्ण बहुभाषी एआई', privacyPillar: 'गोपनीयता और नागरिक सम्मान', redirectPillar: 'सीधा आधिकारिक मार्गदर्शन', disclaimer: 'आधिकारिक नागरिक अस्वीकरण', disclaimerText: 'स्कीम सहाय एक स्वतंत्र नागरिक सूचना मंच है। लाभ की अंतिम स्वीकृति केवल संबंधित सरकारी अधिकारियों के पास है।' },
  te: { transparent: 'పారదర్శక పౌర నిర్మాణం', howTitle: 'స్కీమ్ సహాయ్ ఎలా పనిచేస్తుంది', howSub: 'అధికారిక మంత్రిత్వ శాఖ పత్రాల నుండి ధృవీకరించిన సమాచారంతో పౌర సాధికారత వరకు.', verifiedStep: 'ధృవీకరించిన దశ', compareTitle: 'సంక్షేమ పథకాల అన్వేషణలో స్కీమ్ సహాయ్ ఎందుకు సహాయపడుతుంది', traditional: 'సాంప్రదాయ ప్రభుత్వ శోధన', schemeWay: 'స్కీమ్ సహాయ్ AI మరియు ధృవీకరించిన RAG', sourceBadge: 'పూర్తి పౌర పారదర్శకత', sourceTitle: 'ధృవీకరించిన అధికారిక ప్రభుత్వ వనరులు', sourceIntro: 'స్కీమ్ సహాయ్ సమాధానాలు అధికారిక ప్రభుత్వ పత్రాలు మరియు మంత్రిత్వ శాఖ ఆదేశాలపై ఆధారపడి ఉంటాయి.', ingested: 'సేకరించిన పత్రాలు', grounding: 'ధృవీకరించిన ఆధారం', academic: 'క్రియాశీల విద్యా చక్రం', languages: 'భారతీయ భాషలు', pipeline: 'పత్ర సేకరణ మరియు RAG నిర్మాణం', pipelineSub: 'అధికారిక సర్క్యులర్లను ధృవీకరించగల పౌర సమాచారంగా మార్చే విధానం.', registry: 'అధికారిక పత్రాల రిజిస్ట్రీ', registrySub: 'ధృవీకరించిన ప్రభుత్వ విధాన PDF భాండారం', searchDocs: 'మంత్రిత్వ శాఖ లేదా పత్రం వెతకండి...', document: 'పత్రం పేరు మరియు ID', ministry: 'మంత్రిత్వ శాఖ', version: 'వెర్షన్', verified: 'చివరి ధృవీకరణ', status: 'స్థితి', official: 'అధికారిక లింక్', pdf: 'PDF', aboutBadge: 'స్కీమ్ సహాయ్ పౌర మిషన్', aboutTitle: 'ప్రతి భారతీయ పౌరుడికి సంక్షేమ సేవలు', aboutIntro: 'భారతదేశంలో అనేక సంక్షేమ పథకాలు ఉన్నప్పటికీ, క్లిష్టమైన పత్రాలు, భాషా అడ్డంకులు మరియు విభజిత పోర్టల్స్ వల్ల అర్హులైన వారు అవకాశాలను కోల్పోతున్నారు.', groundingPillar: '100% ప్రాథమిక వనరుల ఆధారం', aiPillar: 'ఆశా: సానుభూతి బహుభాషా AI', privacyPillar: 'గోప్యత మరియు పౌర గౌరవం', redirectPillar: 'నేరుగా అధికారిక మార్గదర్శనం', disclaimer: 'అధికారిక పౌర నిరాకరణ', disclaimerText: 'స్కీమ్ సహాయ్ ఒక స్వతంత్ర పౌర సమాచార వేదిక. ప్రయోజనాల తుది ఆమోదం ప్రభుత్వ అధికారులదే.' },
  ta: { transparent: 'வெளிப்படையான குடிமக்கள் அமைப்பு', howTitle: 'ஸ்கீம் சஹாய் எப்படி செயல்படுகிறது', howSub: 'அதிகாரப்பூர்வ ஆவணங்களிலிருந்து சரிபார்க்கப்பட்ட தகவலுடன் குடிமக்கள் மேம்பாடு வரை.', verifiedStep: 'சரிபார்க்கப்பட்ட படி', sourceBadge: 'முழுமையான குடிமக்கள் வெளிப்படைத்தன்மை', sourceTitle: 'சரிபார்க்கப்பட்ட அதிகாரப்பூர்வ அரசு ஆதாரங்கள்', sourceIntro: 'ஸ்கீம் சஹாய் பதில்கள் அதிகாரப்பூர்வ அரசு ஆவணங்களை அடிப்படையாகக் கொண்டவை.', pipeline: 'ஆவண சேகரிப்பு மற்றும் RAG அமைப்பு', registry: 'அதிகாரப்பூர்வ ஆவணப் பதிவு', aboutBadge: 'ஸ்கீம் சஹாய் குடிமக்கள் பணி', aboutTitle: 'ஒவ்வொரு இந்திய குடிமகனுக்கும் நலத்திட்ட அணுகல்', aboutIntro: 'சிக்கலான ஆவணங்கள் மற்றும் மொழித் தடைகள் காரணமாக பலர் நலத்திட்டங்களைத் தவறவிடுகின்றனர்.', groundingPillar: '100% முதன்மை ஆதார அடிப்படை', aiPillar: 'ஆஷா: அன்பான பல்மொழி AI', privacyPillar: 'தனியுரிமை மற்றும் குடிமக்கள் மரியாதை', redirectPillar: 'நேரடி அதிகாரப்பூர்வ வழிகாட்டல்', disclaimer: 'அதிகாரப்பூர்வ குடிமக்கள் மறுப்பு' },
  kn: { transparent: 'ಪಾರದರ್ಶಕ ನಾಗರಿಕ ವ್ಯವಸ್ಥೆ', howTitle: 'ಸ್ಕೀಮ್ ಸಹಾಯ್ ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ', howSub: 'ಅಧಿಕೃತ ದಾಖಲೆಗಳಿಂದ ಪರಿಶೀಲಿತ ಮಾಹಿತಿಯೊಂದಿಗೆ ನಾಗರಿಕ ಸಬಲೀಕರಣದವರೆಗೆ.', verifiedStep: 'ಪರಿಶೀಲಿತ ಹಂತ', sourceBadge: 'ಸಂಪೂರ್ಣ ನಾಗರಿಕ ಪಾರದರ್ಶಕತೆ', sourceTitle: 'ಪರಿಶೀಲಿತ ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಮೂಲಗಳು', sourceIntro: 'ಸ್ಕೀಮ್ ಸಹಾಯ್ ಉತ್ತರಗಳು ಅಧಿಕೃತ ಸರ್ಕಾರಿ ದಾಖಲೆಗಳನ್ನು ಆಧರಿಸಿವೆ.', pipeline: 'ದಾಖಲೆ ಸಂಗ್ರಹ ಮತ್ತು RAG ರಚನೆ', registry: 'ಅಧಿಕೃತ ದಾಖಲೆ ನೋಂದಣಿ', aboutBadge: 'ಸ್ಕೀಮ್ ಸಹಾಯ್ ನಾಗರಿಕ ಮಿಷನ್', aboutTitle: 'ಪ್ರತಿ ಭಾರತೀಯ ನಾಗರಿಕನಿಗೂ ಕಲ್ಯಾಣದ ಪ್ರವೇಶ', aboutIntro: 'ಸಂಕೀರ್ಣ ದಾಖಲೆಗಳು ಮತ್ತು ಭಾಷಾ ಅಡೆತಡೆಗಳಿಂದ ಅನೇಕ ಅರ್ಹ ನಾಗರಿಕರು ಯೋಜನೆಗಳನ್ನು ಕಳೆದುಕೊಳ್ಳುತ್ತಾರೆ.', groundingPillar: '100% ಪ್ರಾಥಮಿಕ ಮೂಲ ಆಧಾರ', aiPillar: 'ಆಶಾ: ಸಹಾನುಭೂತಿಯ ಬಹುಭಾಷಾ AI', privacyPillar: 'ಗೌಪ್ಯತೆ ಮತ್ತು ನಾಗರಿಕ ಗೌರವ', redirectPillar: 'ನೇರ ಅಧಿಕೃತ ಮಾರ್ಗದರ್ಶನ', disclaimer: 'ಅಧಿಕೃತ ನಾಗರಿಕ ಸೂಚನೆ' },
  ml: { transparent: 'സുതാര്യമായ പൗര സംവിധാനം', howTitle: 'സ്കീം സഹായ് എങ്ങനെ പ്രവർത്തിക്കുന്നു', howSub: 'ഔദ്യോഗിക രേഖകളിൽ നിന്ന് പരിശോധിച്ച വിവരങ്ങളോടെയുള്ള പൗര ശാക്തീകരണത്തിലേക്ക്.', verifiedStep: 'പരിശോധിച്ച ഘട്ടം', sourceBadge: 'പൂർണ്ണ പൗര സുതാര്യത', sourceTitle: 'പരിശോധിച്ച ഔദ്യോഗിക സർക്കാർ ഉറവിടങ്ങൾ', sourceIntro: 'സ്കീം സഹായ് ഉത്തരങ്ങൾ ഔദ്യോഗിക സർക്കാർ രേഖകളെ അടിസ്ഥാനമാക്കുന്നു.', pipeline: 'രേഖ ശേഖരണവും RAG ഘടനയും', registry: 'ഔദ്യോഗിക രേഖ രജിസ്ട്രി', aboutBadge: 'സ്കീം സഹായ് പൗര ദൗത്യം', aboutTitle: 'ഓരോ ഇന്ത്യൻ പൗരനും ക്ഷേമ സേവനങ്ങളിലേക്കുള്ള പ്രവേശനം', aboutIntro: 'സങ്കീർണ്ണ രേഖകളും ഭാഷാ തടസ്സങ്ങളും കാരണം അർഹരായ പലരും പദ്ധതികൾ നഷ്ടപ്പെടുത്തുന്നു.', groundingPillar: '100% പ്രാഥമിക ഉറവിട അടിസ്ഥാനം', aiPillar: 'ആശ: സഹാനുഭൂതിയുള്ള ബഹുഭാഷാ AI', privacyPillar: 'സ്വകാര്യതയും പൗര ബഹുമാനവും', redirectPillar: 'നേരിട്ടുള്ള ഔദ്യോഗിക മാർഗനിർദേശം', disclaimer: 'ഔദ്യോഗിക പൗര നിരാകരണം' },
  mr: { transparent: 'पारदर्शक नागरिक व्यवस्था', howTitle: 'स्कीम सहाय कसे काम करते', howSub: 'अधिकृत कागदपत्रांपासून पडताळलेल्या माहितीसह नागरिक सक्षमीकरणापर्यंत.', verifiedStep: 'पडताळलेला टप्पा', sourceBadge: 'संपूर्ण नागरिक पारदर्शकता', sourceTitle: 'पडताळलेले अधिकृत सरकारी स्रोत', sourceIntro: 'स्कीम सहायची उत्तरे अधिकृत सरकारी कागदपत्रांवर आधारित आहेत.', pipeline: 'कागदपत्र संकलन आणि RAG रचना', registry: 'अधिकृत कागदपत्र नोंदणी', aboutBadge: 'स्कीम सहाय नागरिक मिशन', aboutTitle: 'प्रत्येक भारतीय नागरिकासाठी कल्याणकारी योजनांपर्यंत प्रवेश', aboutIntro: 'कठीण कागदपत्रे आणि भाषेच्या अडथळ्यांमुळे अनेक पात्र नागरिक योजनांपासून वंचित राहतात.', groundingPillar: '100% प्राथमिक स्रोत आधार', aiPillar: 'आशा: सहानुभूतीपूर्ण बहुभाषिक AI', privacyPillar: 'गोपनीयता आणि नागरिकांचा सन्मान', redirectPillar: 'थेट अधिकृत मार्गदर्शन', disclaimer: 'अधिकृत नागरिक सूचना' },
  bn: { transparent: 'স্বচ্ছ নাগরিক ব্যবস্থা', howTitle: 'স্কিম সহায় কীভাবে কাজ করে', howSub: 'সরকারি নথি থেকে যাচাই করা তথ্যের মাধ্যমে নাগরিক ক্ষমতায়ন পর্যন্ত।', verifiedStep: 'যাচাই করা ধাপ', sourceBadge: 'সম্পূর্ণ নাগরিক স্বচ্ছতা', sourceTitle: 'যাচাই করা সরকারি উৎস', sourceIntro: 'স্কিম সহায়ের উত্তর সরকারি নথির উপর ভিত্তি করে তৈরি।', pipeline: 'নথি সংগ্রহ ও RAG কাঠামো', registry: 'সরকারি নথি নিবন্ধন', aboutBadge: 'স্কিম সহায় নাগরিক উদ্যোগ', aboutTitle: 'প্রতিটি ভারতীয় নাগরিকের জন্য কল্যাণের সুযোগ', aboutIntro: 'জটিল নথি ও ভাষার বাধার কারণে অনেক যোগ্য নাগরিক প্রকল্পের সুবিধা পান না।', groundingPillar: '100% প্রাথমিক উৎস ভিত্তি', aiPillar: 'আশা: সহানুভূতিশীল বহুভাষিক AI', privacyPillar: 'গোপনীয়তা ও নাগরিক মর্যাদা', redirectPillar: 'সরাসরি সরকারি নির্দেশনা', disclaimer: 'সরকারি নাগরিক ঘোষণা' },
};

for (const language of ['ta', 'kn', 'ml', 'mr', 'bn'] as LanguageCode[]) copies[language] = { ...en, ...copies[language] };

export const viewT = (language: LanguageCode, key: string) => copies[language][key] || en[key] || key;
